[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://hackx-2.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
