[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "plugmind-backend"
